Issues 4
Karvelia/liquid-log pull request #10
Opened 2017-11-14 21:52 UTC by Karvelia

@ykalemi - Задание №4

2017-11-16 08:24 UTC, ykalemi requested changes

2017-11-16 08:24 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/Parser.java
> +        baseParser.parse();
Ещё один интерфейс для BaseParser - это интересно.

Но есть некоторое замечание, я скопирую с небольшими изменениями комментарий, который писал вашему соседу:

> Но я хотел, чтобы вы избавились от дублирования кода, а теперь цикл обхода строк есть в каждом парсере.
> 
> Я бы хотел, чтобы вы вынесли этот цикл наружу (т.е. вернули в Parser - или в какой-то новый класс, реализующий BaseParser).
> 
> Да, придется немного повозиться с TopParser. Но это не сложно: надо просто в TopTimeParser запоминать время и возвращать его для всех последующих строк, пока не получили новое время. А сам TopParser при этом станет очень простым

Дополнительно хочется, чтобы каждый парсер реализовывал только один интерфейс. Если это парсер времени - то TimeParser, если данных - то DataParser.

2017-11-21 19:36 UTC, programmashka commented
Внесла изменения по Вашим замечаниям.
Надеюсь, что правильно поняла. их

2017-11-22 08:11 UTC, ykalemi approved these changes

2017-11-22 08:11 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/interfaceParsing/DataParser.java
> +                if (timeParser.parseTime(line))
Да, это это почти то, что я хотел

Мне, правда, кажется, что в интерфейсе слишком много методов - parse, prepareDate - можно вообще вынести из интерфейса. Но это на ваш выбор, пусть у вас будет своё решение.

Есть один критичный, на мой взгляд, момент - парсер хранит текущий dataSet. Да и вообще все датасеты, и теперь именно парсер ответственен за вычисление датасета по времени. Мне кажется, это во-первых, усложняет код парсера, во-вторых, снова вернулось небольшое дублирование - вы вынуждены это делать в каждом парсере.

Но можно сейчас пропустить эту задачу - вам придётся избавляться от этого кода в конце концов  когда вы будете решать последнюю на текущий момент задачу: https://github.com/naumen/liquid-log/issues/26
Потому что "нужно сделать каждый парсер отдельным Spring Bean-ом, который не должен хранить никакого состояния".

Т.е. я ставлю +, а озвученную проблему давайте решать позже.

Если не очень понятно описал суть, или не понятно, как избавиться от этой проблемы - пишите.

2017-11-22 18:19 UTC, merged