adding the web version of parsing
Karvelia/liquid-log pull request #6
Opened 2017-11-01 06:22 UTC by Karvelia

@ykalemi - Задание 3

2017-11-01 07:20 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +            new File(nameFile).delete();
С удалением этого файла есть несколько тонких моментов.

1. Если будет выход по ошибке, то удаления файла не будет (почитайте про try-finally)
2. В Java есть специальная конструкция для создания временных файлов - File.createTempFile, и можно настроить автоудаление

Но вообще, можно обойтись без сохранения нового файла - просто передать MultipartFile дальше и потом из него сконструировать InputStream, а всё остальное останется как было.

2017-11-01 07:32 UTC, ykalemi requested changes

2017-11-01 07:32 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +                System.setProperty("parse.mode", modeParsing);
Это достаточно хитро и я подозреваю, что это даже работает. Но это не честно и опасно.

System.setProperty - меняет глобальную переменную окружения. Если будет одновременно две загрузки файлов, то каждая по очереди будет менять эту глобальную переменную.

Ну и на самом деле, в этом же нет никакой необходимости - просто передайте все эти аргументы дальше в App. Смело меняйте сигнатуру и содержимое App. Метод main уже устарел и его название ничего не значит. Пусть у него будут аргументы почти такие же, как у этого контроллера - и всё станет намного проще.

2017-11-01 07:32 UTC, ykalemi commented on src/main/resources/application.properties
> +spring.http.multipart.max-file-size=100MB
круто. А проверяли, это работает и при локальном запуске, и при запуске на openshift?

2017-11-01 07:32 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +        //influxDb.de
Так как у вас нет почти никаких изменений в этом классе, то я подозреваю следующее:

- локально загрузка файла и его парсинг работают только если вы запускаете web-приложение с аргументами как для парсера - т.е. с указанием url и логина-пароля до базы
- на openshift это скорее всего не работает (там не передаются аргументы запуска по умолчанию)

Посмотрите на InfluxDao, как он используется в этом классе и в других местах приложения. В идеале хотелось бы, чтобы запуск веб-приложения был без аргументов доступа к Influx

2017-11-01 18:00 UTC, closed without merging

2017-11-01 20:02 UTC, Karvelia commented on src/main/resources/application.properties
> +spring.http.multipart.max-file-size=100MB
Работает только при локальном запуске. В openshift-е использовать это не получается. 
Это вообще реально сделать?

2017-11-02 13:31 UTC, ykalemi commented on src/main/resources/application.properties
> +spring.http.multipart.max-file-size=100MB
Запустить в openshit? Более чем.

Дело в том, что локально вы продолжаете использовать аргументы запуска типа `-DinfluxDb`. Но эти настройки уже есть в application.properties и приложение уже умеет их использовать - при отображении данных их базы, когда показывает графики.

Т.е. нужно разобраться, куда вообще применяются эти настройки (спойлер - InfluxDao). И почему при отображении нам не нужны аргументы запуска приложения, а при парсинге - нужны.

Ответ тут в Spring и внедрении зависимостей. Вы создаёте InfluxDao "вручную", т.е. через конструктор. При отображении InfluxDao создаётся контейнером Srping и получает параметры настройки напрямую из файла конфигурации.

Можете почитать про Spring и внедрение зависимостей, если хотите разобраться.

Но от System.setProperty лучше избавиться, и передавать параметры с формы напряму в App

2017-11-02 13:36 UTC, ykalemi commented on src/main/resources/application.properties
> +spring.http.multipart.max-file-size=100MB
Про Spring у нас ещё будет лекция. Но будет намного эффективнее, если вы попытаетесь разобраться самостоятельно ещё до лекции.