adding the web version of parsing
Karvelia/liquid-log pull request #7
Opened 2017-11-02 17:37 UTC by Karvelia

@ykalemi - Задание 3.
Учла все замечания. Выполнять загрузку на сервер больших файлов пока не получается, но маленькие грузятся без ошибок. Попробую еще разобраться, но пока рабочая версия такая.

2017-11-02 18:27 UTC, ykalemi requested changes
Ок! Но если есть возможность, я хотел бы, чтобы вы улучшили ваш код.

2017-11-02 18:27 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/PerfhouseApplication.java
> +        /*if (System.getProperty("Parser") != null)
лучше не оставлять в проекте мертвый код

2017-11-02 18:27 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +                App.main(arg, modeParsing, logCheck, influxDAO);
Хочу, чтобы вы пошли немного дальше. 
1. Давайте уберём массив args и вместо этого каждую переменную внутри этого массива передадим в метод main.
2. Далее, имя класса App и метод main уже не несут никакого смысла. Назовите их ближе к тому, что именно они выполняют.

2017-11-02 18:27 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +                e.printStackTrace();
Это не очень хорошая практика - "проглатывать" ошибки. Я надеюсь, мы успеем об этом поговорить на лекциях. Но лучше пробросить ошибку дальше - и она будет обработана фреймворком.

2017-11-02 18:27 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/App.java
>          case "sdng":
Обратите внимание на класс MultipartFile. У него есть метод getInputStream(), который возвращает поток для чтения. Таким образом, вы можете не сохранять на диск какой-то временный файл, а передать прямо сюда MultipartFile с формы, взять у него поток, прочитать этот поток каким-то соответствующим Reader-ом - и отдать в BufferedReader

2017-11-03 21:46 UTC, Karvelia commented
Исправления внесла

2017-11-04 17:17 UTC, ykalemi commented
👍

2017-11-04 17:30 UTC, merged